### ISSUE TITLE
Selected elements not highlighted

### ISSUE THREAD

**Issue by NyxCode** [jakecoffman/jake-theme#1]
Currently, it's not possible to see which UI element is selected - maybe a colored border or slightly brighter background would be helpful. This applies to all UI elements (files in the project view, dropdown menues, ...)
Anyway, great theme, i really enjoy using it

**Comment by jakecoffman** [comment]
I agree, I was having the same issue. I tried the blue inactive selection color because the gray made it feel like I was going to a black & white scheme, bleh.

Thanks for the feedback! It usually takes 2 days for them to publish the update.

**Comment by NyxCode** [comment]
Thanks, it's a pleasure to use it!
