### ISSUE TITLE
Don't seem to match theme, not sure if intentional

### ISSUE THREAD

**Issue by asafarevich** [jakecoffman/jake-theme#2]
![image](https://user-images.githubusercontent.com/30283914/144673647-20412af2-cc5b-4bcd-8cf3-351016d197b0.png)

Should be darker

**Comment by jakecoffman** [comment]
What specifically should be darker?

**Comment by asafarevich** [comment]
Sorry Accidentally deleted the work. Dropdowns. I think they should be darker.

**Comment by jakecoffman** [comment]
It could probably be a bit darker, but I usually see design like this for buttons and dropdowns on other dark themes:

<img width="143" alt="GitHub" src="https://user-images.githubusercontent.com/886768/145891795-fc71ed30-7944-43c4-841e-06187640f944.png">

Usually high contrast accessibility themes look more like this, and I am not a fan:

![Microsoft Teams](https://user-images.githubusercontent.com/886768/145892245-b22c3d19-7ebe-4226-83f4-81260b33601b.png)
